// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getMinIndex
int getMinIndex(Rcpp::IntegerVector v);
RcppExport SEXP _FuzzyDateJoin_getMinIndex(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(getMinIndex(v));
    return rcpp_result_gen;
END_RCPP
}
// inner_fuzzy_date_join_cpp
DataFrame inner_fuzzy_date_join_cpp(DataFrame x, DataFrame y, String x_id_col, String y_id_col, String x_date_col, String y_date_col, int x_intvl_less, int x_intvl_more);
RcppExport SEXP _FuzzyDateJoin_inner_fuzzy_date_join_cpp(SEXP xSEXP, SEXP ySEXP, SEXP x_id_colSEXP, SEXP y_id_colSEXP, SEXP x_date_colSEXP, SEXP y_date_colSEXP, SEXP x_intvl_lessSEXP, SEXP x_intvl_moreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type y(ySEXP);
    Rcpp::traits::input_parameter< String >::type x_id_col(x_id_colSEXP);
    Rcpp::traits::input_parameter< String >::type y_id_col(y_id_colSEXP);
    Rcpp::traits::input_parameter< String >::type x_date_col(x_date_colSEXP);
    Rcpp::traits::input_parameter< String >::type y_date_col(y_date_colSEXP);
    Rcpp::traits::input_parameter< int >::type x_intvl_less(x_intvl_lessSEXP);
    Rcpp::traits::input_parameter< int >::type x_intvl_more(x_intvl_moreSEXP);
    rcpp_result_gen = Rcpp::wrap(inner_fuzzy_date_join_cpp(x, y, x_id_col, y_id_col, x_date_col, y_date_col, x_intvl_less, x_intvl_more));
    return rcpp_result_gen;
END_RCPP
}
// left_fuzzy_date_join_cpp
DataFrame left_fuzzy_date_join_cpp(DataFrame x, DataFrame y, String x_id_col, String y_id_col, String x_date_col, String y_date_col, int x_intvl_less, int x_intvl_more);
RcppExport SEXP _FuzzyDateJoin_left_fuzzy_date_join_cpp(SEXP xSEXP, SEXP ySEXP, SEXP x_id_colSEXP, SEXP y_id_colSEXP, SEXP x_date_colSEXP, SEXP y_date_colSEXP, SEXP x_intvl_lessSEXP, SEXP x_intvl_moreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type y(ySEXP);
    Rcpp::traits::input_parameter< String >::type x_id_col(x_id_colSEXP);
    Rcpp::traits::input_parameter< String >::type y_id_col(y_id_colSEXP);
    Rcpp::traits::input_parameter< String >::type x_date_col(x_date_colSEXP);
    Rcpp::traits::input_parameter< String >::type y_date_col(y_date_colSEXP);
    Rcpp::traits::input_parameter< int >::type x_intvl_less(x_intvl_lessSEXP);
    Rcpp::traits::input_parameter< int >::type x_intvl_more(x_intvl_moreSEXP);
    rcpp_result_gen = Rcpp::wrap(left_fuzzy_date_join_cpp(x, y, x_id_col, y_id_col, x_date_col, y_date_col, x_intvl_less, x_intvl_more));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FuzzyDateJoin_getMinIndex", (DL_FUNC) &_FuzzyDateJoin_getMinIndex, 1},
    {"_FuzzyDateJoin_inner_fuzzy_date_join_cpp", (DL_FUNC) &_FuzzyDateJoin_inner_fuzzy_date_join_cpp, 8},
    {"_FuzzyDateJoin_left_fuzzy_date_join_cpp", (DL_FUNC) &_FuzzyDateJoin_left_fuzzy_date_join_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_FuzzyDateJoin(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
