# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Inner fuzzy date join
#'
#' @param x X data frame.
#' @param y Y data frame.
#' @param x_id_col Name of column in X data frame with IDs.
#' @param y_id_col Name of column in Y data frame with IDs.
#' @param x_date_col Name of column in X data frame with dates.
#' @param y_date_col Name of column in Y data frame with dates.
#' @param x_intvl_less Number of days before X date to match to Y date. Defaults to 0.
#' @param x_intvl_more Number of days after X date to match to Y date. Defaults to 0.
#' @export
InnerRows <- function(x, y, x_id_col, y_id_col, x_date_col, y_date_col, x_intvl_less = 0L, x_intvl_more = 0L) {
    .Call(`_FuzzyDateJoin_InnerRows`, x, y, x_id_col, y_id_col, x_date_col, y_date_col, x_intvl_less, x_intvl_more)
}

#' Left fuzzy date join
#'
#' @param x X data frame.
#' @param y Y data frame.
#' @param x_id_col Name of column in X data frame with IDs.
#' @param y_id_col Name of column in Y data frame with IDs.
#' @param x_date_col Name of column in X data frame with dates.
#' @param y_date_col Name of column in Y data frame with dates.
#' @param x_intvl_less Number of days before X date to match to Y date. Defaults to 0.
#' @param x_intvl_more Number of days after X date to match to Y date. Defaults to 0.
#' @export
OuterLeftRows <- function(x, y, x_id_col, y_id_col, x_date_col, y_date_col, x_intvl_less = 0L, x_intvl_more = 0L) {
    .Call(`_FuzzyDateJoin_OuterLeftRows`, x, y, x_id_col, y_id_col, x_date_col, y_date_col, x_intvl_less, x_intvl_more)
}

#' Get index of minimum value in integer vector
#'
#' @param v An integer vector.
#' @export
getMinIndex <- function(v) {
    .Call(`_FuzzyDateJoin_getMinIndex`, v)
}

